Repository nodejs/build, pull requests merged in 2018-09, with the labels that each got.

#1480 jenkins: no freebsd10 for Node 11
  jenkins/scripts/VersionSelectorScript.groovy
Labels: ci-public, ci-release

#1494 ci-change: timeout in post-build-status
  jenkins/pipelines/post-build-status-update.jenkinsfile
Labels: ci-change, ci-public

#1025 jenkins: add llnode pipeline and shell scripts
  jenkins/pipelines/llnode-pipeline.jenkinsfile
  jenkins/scripts/common/colors.sh
  jenkins/scripts/common/getLLDB.sh
  jenkins/scripts/common/getNode.sh
  jenkins/scripts/common/helpers.sh
  jenkins/scripts/llnode-continuous-integration.sh
Labels: ci-job-request, ci-public
