Repository nodejs/build, pull requests merged in 2019-04, with the labels that each got.

#1723 ansible: update minimum gcc on linux-ppc64le to gcc-6
  ansible/roles/baselayout/tasks/partials/repo/ubuntu1404.yml
  ansible/roles/baselayout/vars/main.yml
  ansible/roles/jenkins-worker/meta/main.yml
  ansible/roles/jenkins-worker/tasks/main.yml
  jenkins/scripts/select-compiler.sh
Labels: enhancement, platform:ppc

#1777 jenkins: new "release-sources" labels for source, headers, docs
  jenkins/scripts/VersionSelectorScript.groovy
Labels: ci-change, ci-public, ci-release

#1763 Add support for Centos7/ppc64
  ansible/inventory.yml
  ansible/roles/baselayout/tasks/partials/repo/centos7.yml
  ansible/roles/baselayout/vars/main.yml
  ansible/roles/java-base/tasks/main.yml
  jenkins/scripts/VersionSelectorScript.groovy
  jenkins/scripts/select-compiler.sh
Labels: ci-change, ci-public, ci-release, platform:ppc
