Repository nodejs/build, pull requests merged in 2020-01, with the labels that each got.

#1745 pipelines: add lint-py to linter pipeline
  jenkins/pipelines/node-linter.jenkinsfile
  jenkins/pipelines/node-test-pull-request-lite-pipeline.jenkinsfile
Labels: ci-public, enhancement

#2142 doc: add OFFBOARDING.md and update ONBOARDING.md
  OFFBOARDING.md
  ONBOARDING.md
Labels: doc

#2141 doc: add GOVERNANCE.md and clean up docs
  GOVERNANCE.md
  README.md
  ansible/MANUAL_STEPS.md
  doc/non-ansible-configuration-notes.md
  doc/process/special_access_to_build_resources.md
  doc/resources.md
  doc/services.md
  doc/ssh.md
Labels: doc

#1325 refresh incantations
  doc/jenkins-guide.md
Labels: bug, doc, enhancement

#1947 coverage: add the needed CSS from the main site
  jenkins/scripts/coverage/generate-index-html.py
  jenkins/scripts/coverage/styles.css
Labels: build-agenda
