Repository nodejs/build, pull requests merged in 2020-09, with the labels that each got.

#2407 jenkins: remove old macos from versionselector
  jenkins/scripts/VersionSelectorScript.groovy
Labels: ci-public, platform:osx

#2436 doc: add security-triage team to security matrix
  static-assets/jenkins-authorization-normal.png
  static-assets/jenkins-authorization-sec.png
Labels: ci-public, doc

#2437 ansible: changes for z/OS 2.4 VMs
  ansible/ansible.cfg
  ansible/inventory.yml
  ansible/roles/jenkins-worker/tasks/main.yml
  ansible/roles/jenkins-worker/templates/git-wrapper.j2
  ansible/roles/jenkins-worker/vars/main.yml
Labels: ansible, ci-public, platform:zos
