Repository nodejs/build, pull requests merged in 2023-07, with the labels that each got.

#3407 jenkins: add vs2022 to version selector script
  jenkins/scripts/VersionSelectorScript.groovy
Labels: ansible, platform:windows

#3421 Improved manual steps for macos
  ansible/MANUAL_STEPS.md
Labels: enhancement, doc, platform:osx

#3431 ansible: replace fedora34-x64-1 with fedora38-x64-2
  ansible/inventory.yml
Labels: ansible, platform:linux-intel
