Repository nodejs/build, pull requests merged in 2025-02, with the labels that each got.

#3868 Remove MacStadium release from inventory
  ansible/inventory.yml
Labels: platform:osx

#3869 Remove Orka test from inventory
  ansible/inventory.yml
Labels: test, platform:osx, orka

#3870 Remove Orka release from inventory
  ansible/inventory.yml
Labels: platform:osx, orka

#3871 Remove MacStadium test from inventory
  ansible/inventory.yml
Labels: test, platform:osx

#4016 ansible,win: add ccache
  ansible/roles/visual-studio/files/ccache.conf
  ansible/roles/visual-studio/tasks/main.yml
Labels: build, ansible, platform:windows
